### PR TITLE
knplabs v2

### PR DESCRIPTION
**Pull request by PavelJurasek**
PR targets your dev branch

### CODE REVIEW

**Comment by PavelJurasek** [comment]
Any idea why CI was not triggered?

**Comment by Scorpio256** [comment]
Any news on update?

**Comment by hermajan** [comment]
It looks like it is working on knplabs/doctrine-behaviors 2.2.0 at least for Translatable behaviour. Currently I don't use others.

Please could this PR be merged and released @f3l1x? Or is there something needed to be done?

**Comment by hermajan** [comment]
Thanks for merging @f3l1x. Could it be merged with #12 into master and release it?

**Comment by f3l1x** [comment]
#12 needs some work, there are conflicts. Can you take a look?

**Pull request merged**
